### ISSUE TITLE
Some paragraph title font does not correspond with the official template

### ISSUE THREAD

**Issue by WXin2865896370** [NemoYuan2008/SJTU-Thesis-Proposal#1]
Word version of the opening report title font size is show as follows:
<img width="633" alt="Snipaste_2024-12-24_19-41-56" src="https://github.com/user-attachments/assets/b1246904-536d-4fb4-9c99-c7d552403519" />
But the fonts given by the template don't correspond.
<img width="951" alt="Snipaste_2024-12-24_19-44-54" src="https://github.com/user-attachments/assets/8a546bf8-032d-477c-ac87-fe20c107873d" />

**Comment by NemoYuan2008** [comment]
The font displayed in the MS Word version seems incorrect in your screenshot, probably because you did not install the font `仿宋_GB2312`. After installing the font, the appearance of the MS Word version will change. The LaTeX version uses the font `simfang.ttf` (i.e., 仿宋) on Windows, which actually matches the MS Word version.

You do not need to install the font `仿宋_GB2312` for the LaTeX version. It just makes the MS Word correct.

**Comment by WXin2865896370** [comment]
Thank you, the problem has been solved.
